def calculator():
  print("what is your name?")
  variable = input()
  print("Hello",variable)
  print("I´m Havana Unana your new ĆΔŁĆỮŁΔŦØŘ ૮ ˶ᵔ ᵕ ᵔ˶ ა")
  print("ƤŁ€ΔŞ€ ǤƗV€ Μ€ Δ ŇỮΜβ€Ř ΔŇĐ Δ €ЖƤØŇ€ŇŦ")
  Base = input()
  Exponent = input()
  result = int(Base)**(1/int(Exponent))
  print("̷Y̷̷o̷̷u̷̷r̷ ̷r̷̷o̷̷o̷̷t̷ ̷i̷̷s", result)
  print("Was I helpful??? ⸜(｡˃ ᵕ ˂ )⸝")
  no = input()
  print("No!?!?!?!? (╥﹏╥)")
  print("Well, then i´m going to self-destruct bye...")

calculator()
