def robotdog():
  print ("Hello, please insert the distance that the dog advanced the first time")
  distance1 = input()
  print ("Please insert the distance that the dog advanced the second time")
  distance2 = input()
  print ("Please insert the distance that the dog advanced the third time")
  distance3 = input()
  print ("Please write the time it took the first time")
  first = input()
  print ("Please write the time it took the second time")
  second = input()
  print ("Finally, please write the time it took the third time")
  third = input()
  result1 = float(distance1)/float(first)
  result2 = float(distance2)/float(second)
  result3 = float(distance3)/float(third)
  print ("The velocity of the first iteration was",result1)
  print ("The velocity of the second iteration was",result2)
  print ("The velocity of the third iteration was",result3)
  print ("Would you like to know the average velocity? (please answer in lowercase letters)")
  knowaverage = input()
  averagevelocity = (float(result1)+float(result2)+float(result3))/3
  if (knowaverage == "no"): print ("Ok! Have a nice day")
  if (knowaverage == "yes"): print ("The average velocity is",averagevelocity)
  print ("Would you like to know the average acceleration? (please answer in lowercase letters)")
  knowaverageacc = input()
  averagetime = (float(first)+float(second)+float(third))/3
  averageacceleration = float(averagevelocity)/float(averagetime)
  if (knowaverageacc == "no"): print ("Ok! Have a nice day")
  if (knowaverageacc == "yes"): print ("The average acceleration is",averagetime)
  
robotdog()
